const notice = [
    {
        _id: 1,
        src: "WBBPE_NOTICE/Notification%20of%20publication%20of%20the%20result%20TET-2017.pdf",
        title: " NOTIFICATION OF PUBLICATION OF THE RESULT OF THE TEACHER ELIGIBILITY TEST (TET) (PRIMARY I TO V)-2017-EXAMINATION, HELD OFFLINE ON JANUARY 31, 2021 THROUGHOUT THE STATE OF WEST BENGAL CONDUCTED BY WEST BENGAL BOARD OF PRIMARY EDUCATION",
        img: "images/new.gif"
    },
    {
        _id: 2,
        src: "WBBPE_NOTICE/Notification%20of%20publication%20of%20the%20result%20TET-2017.pdf",
        title: " NOTIFICATION OF PUBLICATION OF THE RESULT OF THE TEACHER ELIGIBILITY TEST (TET) (PRIMARY I TO V)-2017-EXAMINATION, HELD OFFLINE ON JANUARY 31, 2021 THROUGHOUT THE STATE OF WEST BENGAL CONDUCTED BY WEST BENGAL BOARD OF PRIMARY EDUCATION",
        img: "images/new.gif"
    },
    {
        _id: 3,
        src: "WBBPE_NOTICE/Notification%20of%20publication%20of%20the%20result%20TET-2017.pdf",
        title: " NOTIFICATION OF PUBLICATION OF THE RESULT OF THE TEACHER ELIGIBILITY TEST (TET) (PRIMARY I TO V)-2017-EXAMINATION, HELD OFFLINE ON JANUARY 31, 2021 THROUGHOUT THE STATE OF WEST BENGAL CONDUCTED BY WEST BENGAL BOARD OF PRIMARY EDUCATION",

    },
    {
        _id: 4,
        src: "WBBPE_NOTICE/Notification%20of%20publication%20of%20the%20result%20TET-2017.pdf",
        title: " NOTIFICATION OF PUBLICATION OF THE RESULT OF THE TEACHER ELIGIBILITY TEST (TET) (PRIMARY I TO V)-2017-EXAMINATION, HELD OFFLINE ON JANUARY 31, 2021 THROUGHOUT THE STATE OF WEST BENGAL CONDUCTED BY WEST BENGAL BOARD OF PRIMARY EDUCATION",

    },
    {
        _id: 5,
        src: "WBBPE_NOTICE/Notification%20of%20publication%20of%20the%20result%20TET-2017.pdf",
        title: " NOTIFICATION OF PUBLICATION OF THE RESULT OF THE TEACHER ELIGIBILITY TEST (TET) (PRIMARY I TO V)-2017-EXAMINATION, HELD OFFLINE ON JANUARY 31, 2021 THROUGHOUT THE STATE OF WEST BENGAL CONDUCTED BY WEST BENGAL BOARD OF PRIMARY EDUCATION",

    }
]
export default notice;